=== joaopcg10/PRI2020/TP2/pr.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="project_record">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="bloco_de_dados"/>
        <xs:element ref="workteam"/>
        <xs:element ref="abstract"/>
        <xs:element ref="deliverables"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="bloco_de_dados">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="titulo"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="subtitulo"/>
        <xs:element ref="begin_date"/>
        <xs:element ref="end_date"/>
        <xs:element ref="supervisor"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="titulo" type="xs:string"/>
  <xs:element name="subtitulo" type="xs:string"/>
  <xs:element name="begin_date" type="xs:string"/>
  <xs:element name="end_date" type="xs:string"/>
  <xs:element name="supervisor">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.supervisor"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.supervisor">
    <xs:attribute name="url" use="required"/>
  </xs:attributeGroup>
  <xs:element name="workteam">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="elemento"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="elemento">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nome"/>
        <xs:element ref="numero"/>
        <xs:element ref="email"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="nome" type="xs:string"/>
  <xs:element name="numero" type="xs:string"/>
  <xs:element name="email">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.email"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.email">
    <xs:attribute name="url"/>
  </xs:attributeGroup>
  <xs:element name="abstract">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="paragrafo"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="paragrafo">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="bold"/>
        <xs:element ref="italico"/>
        <xs:element ref="sublinhado"/>
        <xs:element ref="link"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="bold" type="xs:string"/>
  <xs:element name="italico" type="xs:string"/>
  <xs:element name="sublinhado" type="xs:string"/>
  <xs:element name="deliverables">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="link"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="link">
    <xs:complexType mixed="true">
      <xs:attributeGroup ref="attlist.link"/>
    </xs:complexType>
  </xs:element>
  <xs:attributeGroup name="attlist.link">
    <xs:attribute name="url" use="required"/>
  </xs:attributeGroup>
</xs:schema>

=== joaopcg10/PRI2020/TP2/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<project_record xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="file:/C:/Users/joaop/Desktop/pr.xsd">
    <bloco_de_dados>
        
        <titulo> Estrutura de Armazenamento e Apresentação para Relatórios Académicos e Teses de Mestrado </titulo>
        
        <subtitulo> MICEI 2001/2 </subtitulo>
        
        <begin_date> Julho 2002 </begin_date>
        
        <end_date> Julho 2002 </end_date>
        
        <supervisor url="http://www.di.uminho.pt/~jcr"> José Carlos Ramalho </supervisor>
    </bloco_de_dados>
    
    <workteam>
        
        <elemento>
            <nome> Eurico Alexandre Teixeira Borges </nome>
            <numero> numero1 </numero>
            <email url="mailto:eurico.borges@sonae.pt"> eurico.borges@sonae.pt </email>
        </elemento>
    
    </workteam>
    
    <abstract>
        
        <paragrafo>
            Quando um relatório ou uma tese têm de ser apresentados em vários formatos finais nem sempre é fácil a transformação do formato usado inicialmente no formato desejado. A utilização de <bold> XML </bold> (<link url="http://www.w3.org/XML/">http://www.w3.org/XML/</link>) como estrutura de suporte documental permite isolar esse factor. Facilmente se gera um formato de apresentação a partir de um documento devidamente estruturado em <bold>XML</bold>. Seja para <bold>HTML</bold>, <bold>PDF</bold> ou <bold>RTF</bold>, entre outros. O trabalho realizado propõe um método de estuturação de dados em XML para satisfazer as necessidades específicas de documentação em Relatórios Académicos e Teses de Mestrado. A estrutura é validada por um <bold>XML Schema</bold> (<link url="http://www.w3.org/2001/XMLSchema-instance">http://www.w3.org/2001/XMLSchema-instance</link>) e recorre ao <bold>XSLT</bold> (<link url="http://www.w3.org/1999/XSL/Transform">http://www.w3.org/1999/XSL/Transform</link>) para transformar e gerar uma apresentação em <bold>HTML</bold> a partir do ficheiro <bold>XML</bold>. Um relatório do trabalho académico de Processamento Estruturado de Documentos é apresentado como exemplo auto-demonstrativo.
        </paragrafo>
    
    </abstract>
    
    <deliverables>
        
        <link url="http://www4.di.uminho.pt/~jcr/PROJS/micei2002/eurico/EBdocSchema.html">
            XML Schema (source documentada graficamente)
        </link>
        
        <link url="http://www4.di.uminho.pt/~jcr/PROJS/micei2002/eurico/EBrelatorio.xslt">
            Style Sheet XSLT
        </link>
        
        <link url="http://www4.di.uminho.pt/~jcr/PROJS/micei2002/eurico/EBrelatorio2.xml">
            Ficheiro source XML (sem transformações)
        </link>
        
        <link url="http://www4.di.uminho.pt/~jcr/PROJS/micei2002/eurico/EBrelatorio.html">
            Apresentação HTML após transformações XSLT sobre o XML
        </link>
        
    </deliverables>
    
</project_record>
